from typing import Protocol

from todoapp.domain.todo_list import ToDoList
from todoapp.domain.models import ToDoSummary


class ToDoRepository(Protocol):
    def load_todo(self, todo_id: str) -> ToDoList | None: ...

    def save_todo(self, todo: ToDoList) -> None: ...

    def delete_todo(self, todo_id: str) -> bool: ...

    def get_todos(self) -> list[ToDoSummary]: ...

    def update_todo_summary(self, todo: ToDoList) -> None: ...

    def register_todo_summary(self, todo: ToDoList) -> None: ...

    def get_todo_summary_by_id(self, todo_id: str) -> ToDoSummary | None: ...

    def get_todo_summary_by_title(self, title: str) -> ToDoSummary | None: ...
