services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: mytodo-backend:v0.1.0
    container_name: mytodo-backend-container
    ports:
      - "8000:8000"
    environment:
      DATA_DIR: /app/data
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: mytodo-frontend:v0.1.0
    container_name: mytodo-frontend-container
    depends_on:
      - backend
    ports:
      - "5173:5173"
